---
- hosts: all
  remote_user: clduser
  tasks:
  - name: remove novalocal from hostname
    hostname: name={{ansible_hostname}}
    notify:
      - restart logstash
  - name: install java
    yum: name=java-1.7.0-openjdk state=present update_cache=yes
  - name: install logstash 5.2
    yum: name=https://download.elastic.co/logstash/logstash/packages/centos/logstash-1.5.2-1.noarch.rpm state=present  update_cache=yes
  - name: ensure logstash is running (and enable it at boot)
    service: name=logstash state=started enabled=yes
  handlers:
    - name: restart logstash
      service: name=logstash state=restarted
